# Servo parameters
# https://github.com/mike4192/spotMicro/blob/master/servo_calibration.md#description-of-servo-configuration-values
num_servos: 12
servo_max_angle_deg: 82.5
# NOTE 1: 'center_angle_deg' MUST NOT BE GREATHER THAN 'servo_max_angle_deg'
# NOTE 2: 'range' must be less or equal than 'center'
#
# center: 306 (12-bit PWM) = 1.5 uS pulse width
# Equation:
#  B = D * f * 4096 / 1E6
# Where:
# - B: 12-bit digital value
# - D: duty cycle
# - f: PWM frequency (50 Hz)
#
RF_3: {num: 9,  center: 324, range: 269.5, direction: 1, center_angle_deg:  89.39}
RF_2: {num: 8,  center: 314, range: 403.3, direction: 1, center_angle_deg:   0}
RF_1: {num: 7,  center: 306, range: 374, direction: -1, center_angle_deg:   4.41}

RB_3: {num: 3,  center: 306, range: 385, direction: 1, center_angle_deg: 91.29} # low
RB_2: {num: 2,  center: 306, range: 381.3, direction: 1, center_angle_deg:   -37.21} #high

RB_1: {num: 1,  center: 306, range: 381.3, direction: 1, center_angle_deg:   -3.46} #hip

LB_3: {num: 6,  center: 306, range: 385, direction: 1, center_angle_deg:   -94.29}
LB_2: {num: 5,  center: 306, range: 403.3, direction: 1, center_angle_deg:    91.23}
LB_1: {num: 4,  center: 306, range: 381.3, direction: -1, center_angle_deg:  -6.92}
LF_3: {num: 12, center: 306, range: 394.2, direction: 1, center_angle_deg:   -85.4}
LF_2: {num: 11, center: 306, range: 403.3, direction: 1, center_angle_deg:  85.91}
LF_1: {num: 10, center: 306, range: 385, direction: 1, center_angle_deg:  4.29}
